version: v1

labels:
  - label: kind/feature
    matcher:
      title: "^feat\\(.+\\): .+"

  - label: kind/fix
    matcher:
      title: "^fix\\(.+\\): .+"

  - label: kind/chore
    matcher:
      title: "^chore\\(.+\\): .+"

  - label: kind/refactor
    matcher:
      title: "^refactor\\(.+\\): .+"

  - label: kind/docs
    matcher:
      title: "^docs\\(.+\\): .+"

  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/apps
    sync: true
    matcher:
      files: "apps/**"

  - label: area/examples
    sync: true
    matcher:
      files: "examples/**"

  - label: area/modules
    sync: true
    matcher:
      files: "modules/**"

  - label: area/packages
    sync: true
    matcher:
      files: "packages/**"

checks:
  - context: "Semantic Pull Request"
    url: "https://github.com/DeFiCh/jellyfish/blob/main/.github/labeler.yml"
    description:
      success: Ready for review & merge.
      failure: Missing semantic title or label for merge.
    labels:
      any:
        - kind/feature
        - kind/fix
        - kind/chore
        - kind/refactor
        - kind/docs
