[build]
publish = "website/build/"
command = "npm run all:build && npm run all:docs && npm run build --workspace=website"

[[headers]]
for = "/img/*"
[headers.values]
Cross-Origin-Resource-Policy = "same-origin"
