version: '3.7'

services:
  defi-blockchain:
    image: defi/defichain:2.6.0
    ports:
      - "8554:8554"
    command: >
      defid
      -printtoconsole
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=playground
      -rpcpassword=playground
      -rpcworkqueue=1000
      -masternode_operator=mswsMVsyGMj1FzDMbbxw2QW3KvQAv2FKiy
      -disablewallet=1
      -jellyfish_regtest=1
      -txnotokens=0
      -logtimemicros
      -txindex=1
      -acindex=1
      -amkheight=0
      -bayfrontheight=1
      -bayfrontgardensheight=2
      -clarkequayheight=3
      -dakotaheight=4
      -dakotacrescentheight=5
      -eunosheight=6
      -eunospayaheight=7
      -fortcanningheight=8
      -fortcanningmuseumheight=9
      -fortcanninghillheight=10

  defi-whale:
    build:
      context: ../..
      args:
        APP: whale
    ports:
      - "3000:3000"
    depends_on:
      - defi-blockchain
    environment:
      WHALE_DEFID_URL: http://playground:playground@defi-blockchain:8554
      WHALE_NETWORK: mainnet
      WHALE_VERSION: v0
      WHALE_DATABASE_PROVIDER: level
      WHALE_DATABASE_LEVEL_LOCATION: level/index