name: CI Size

on:
  pull_request:
    branches: [ main ]

jobs:
  size:
    name: Size Limit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - uses: andresz1/size-limit-action@c53e18c847d5eb13f61754c45f3fbfc3aa5c17cc
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build
