name: Release Drafter

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@e5ccf147077e46b0225a80bbe314d795d77bb7a2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
