name: Release Drafter

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@436492609a0c75979acf131d57f61b5321571950
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
